# Permalinks
permalink:        pretty

# Setup
title:            Stevo
tagline:          Full stack web developer, here to help you.
url:              http://stephenvovan.com
paginate:         1
baseurl:          /
author:
  name:           Stephen Vo Van
  url:            https://twitter.com/vovantics
  email:          stephenvovan@gmail.com

# Links
links:
  - name:         Home
    url:          /
  - name:         Services
    url:          /services/
  - name:         Projects
    url:          /projects/

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/vovantics/vovantics.github.io
